pypi setup - add readme on PyPI
vertexproject/synapse pull request #1872
Opened 2020-09-04 13:35 UTC by wesinator

2020-09-04 14:28 UTC, vEpiphyte commented on setup.py
> +with open('README.rst'), encoding='utf-8') as f:
This open statement is invalid python syntax.

2020-09-04 14:29 UTC, vEpiphyte requested changes
PR needs to be valid syntax

2020-09-04 17:06 UTC, wesinator commented
> PR needs to be valid syntax

crap, it was a typo from example. Fixed

2020-09-16 16:35 UTC, vEpiphyte commented on setup.py
> +with open('README.rst', encoding='utf-8') as f:
@wesinator Would you mind updating this to be conditional, similar to how this is done?
https://github.com/vertexproject/common-tools/blob/master/setup.py#L21

2020-09-16 16:35 UTC, vEpiphyte commented on setup.py
> +with open('README.rst', encoding='utf-8') as f:
and set the type so it is not ambiguous

2020-09-21 13:59 UTC, vEpiphyte approved these changes

2020-09-21 13:59 UTC, vEpiphyte commented
Testing this on testpypi - looks nice.

![image](https://user-images.githubusercontent.com/26100278/93776058-ad942700-fc12-11ea-89e3-1d18b941bfc5.png)

2020-09-21 14:00 UTC, merged