Py38 feature prep
vertexproject/synapse pull request #1921
Opened 2020-10-19 21:55 UTC by vEpiphyte

2020-10-22 15:44 UTC, vEpiphyte commented on .circleci/config.yml
> +    description: "Check docker smoke test results"
words

2020-10-22 15:44 UTC, vEpiphyte commented on .circleci/config.yml
> +            - python37
py38

2020-10-22 15:44 UTC, vEpiphyte commented on .circleci/config.yml
> +            - python37
replays

2020-10-22 19:03 UTC, jnwatson commented on setup.py
>          'lark-parser>=0.9.0,<0.10.0',
Please to update to `lark-parser>=0.9.0,<0.11.0`

2020-10-28 15:40 UTC, jnwatson requested changes

2020-10-28 15:40 UTC, jnwatson commented on .circleci/config.yml
> +    description: "Common Pypi prolouge"
speeling "prologue"

2020-10-28 19:05 UTC, merged