Feature stormprims docs
vertexproject/synapse pull request #2034
Opened 2020-12-29 21:48 UTC by vEpiphyte

2020-12-30 03:34 UTC, invisig0th requested changes

2020-12-30 03:34 UTC, invisig0th commented on synapse/lib/stormlib/model.py
> +    Implemen the Storm API for a Property.
Implement?

2020-12-30 03:34 UTC, invisig0th commented on synapse/lib/stormlib/model.py
> +    def _propName(self):
Not 100% sure i'm digging the fact that every deref property access ends up incurring the cost of an additional function call frame with this pattern.  Not against it, but lets discuss :)

2020-12-30 03:34 UTC, invisig0th commented on synapse/lib/stormlib/model.py
> +        Set the locked property for model element.
maybe `for a deprecated model element` just for further clarity

2020-12-30 03:34 UTC, invisig0th commented on synapse/lib/stormtypes.py
> +        OMG SO COOL
hahaha, are these the new FIXME? :D

2020-12-30 03:34 UTC, invisig0th commented on synapse/lib/stormtypes.py
> +    Implements the STORM api for a View instance.
Should probably `STORM` -> `Storm` while we're here

2021-01-22 18:52 UTC, vEpiphyte commented on synapse/lib/autodoc.py
> +def docStormPrims2(page: RstHelp, docinfo, linkprefix: str, islib=False):
remove type hints

2021-01-22 18:53 UTC, vEpiphyte commented on synapse/lib/autodoc.py
> +def docStormPrims2(page: RstHelp, docinfo, linkprefix: str, islib=False):
real docs and rename

2021-01-22 18:53 UTC, vEpiphyte commented on synapse/lib/stormhttp.py
> +        {
Add headers

2021-01-22 19:14 UTC, vEpiphyte commented on synapse/tools/autodoc.py
> +    # XXX SO all this is custom FOR mainline types.
comment

2021-01-22 20:38 UTC, vEpiphyte commented on synapse/cortex.py
> +        return await self.cell.getStormDocs()
There are other generic "give me information about the cortex" apis which this could fit into

2021-01-22 20:43 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        # I just need to check rtype here and if its a function; then
cleanup comment

2021-01-22 20:51 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +class Pipe(StormType):  # FIXME prim?
OBE Comment

2021-01-22 20:52 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +    typename = 'storm:pipe'
rename this constant

2021-01-22 20:54 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        self.locls['name'] = self.name
add test

2021-01-22 20:55 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        '''
all these methods need to move

2021-01-22 20:58 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +    # TODO Example when we have the stormrst stable
obe comment

2021-01-22 20:59 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        # FIXME - This is an API change if we use it.
discuss

2021-01-22 21:00 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        # TODO defv is unused.
obe comment.

2021-01-22 21:01 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +        '''
dead code

2021-01-22 21:02 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +            'name': 'GetFormcount',
getFormCounts() ?

2021-01-22 21:03 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +@registry.registerType  # XXXTODO
dead comment

2021-01-22 21:03 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +
dead code

2021-01-22 21:04 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> -        todo = s_common.todo('enableTrigger', iden)
this dead  code.

2021-01-22 21:05 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +                    'desc': '',
line

2021-01-27 17:47 UTC, invisig0th approved these changes

2021-01-27 21:56 UTC, merged