WIP: Feature aha docs
vertexproject/synapse pull request #2089
Opened 2021-02-22 14:25 UTC by vEpiphyte

2021-02-22 14:25 UTC, vEpiphyte commented on docs/conf.py
> +    # app.connect('builder-inited', convert_ipynb)
remove this

2021-02-22 15:02 UTC, vEpiphyte commented on docs/synapse/devguides/devops_aha.rst
> +SVCINFO notes
Fill this out

2021-02-22 15:04 UTC, vEpiphyte commented on synapse/lib/aha.py
> +                                   mesg='Name must contain at least one "."')
svcname

2021-02-22 19:32 UTC, invisig0th requested changes

2021-02-22 19:32 UTC, invisig0th commented on docs/synapse/devguides/devops_aha.rst
> +service discovery when multiple Synapse services are being deployed in a
`an environment`

2021-02-22 19:32 UTC, invisig0th commented on docs/synapse/devguides/devops_aha.rst
> +environment. This page covers what how Aha works, what services the AhaCell
`what how Aha works` ? :)

2021-02-24 14:37 UTC, invisig0th approved these changes

2021-02-24 14:49 UTC, merged