Allow subquery edit assignments to have a return()
vertexproject/synapse pull request #2132
Opened 2021-03-25 17:52 UTC by jnwatson

As an alternative to yielding a single node that the secondary query would be set to, this allows just returning a value from the subquery.

2021-03-25 20:23 UTC, invisig0th approved these changes

2021-03-26 13:13 UTC, invisig0th requested changes

2021-03-26 13:13 UTC, invisig0th commented on synapse/lib/ast.py
> +            return hasast
Would you mind adding a test to mop up covering this line?  it's small but important :D

2021-03-30 14:19 UTC, invisig0th approved these changes

2021-03-30 20:27 UTC, jnwatson commented
Combined with another PR

2021-03-30 20:27 UTC, closed without merging