More useful output when using $lib.print on StormTypes
vertexproject/synapse pull request #2185
Opened 2021-05-11 14:37 UTC by Cisphyx

Resolves SYN-1527

2021-05-11 15:28 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> +            mesg = await toprim(mesg)
This does have some potentially backwards behaviors - for example:

```cli> storm [inet:ipv4=1.2.3.4] $lib.print($node) | spin
Executing query at 2021/05/11 15:22:03.611
...
Node{(('inet:ipv4', 16909060), {'iden': '20153b758f9d5eaaa38e4f4a65c36da797c3e59e549620fa7c4895e1a920991f', 'tags': {}, 'props': {'.created': 1620746523790, 'type': 'unicast'}, 'tagprops': defaultdict(<class 'dict'>, {}), 'nodedata': {}})}
complete. 0 nodes in 187 ms (0/sec).

vs 


cli> storm [inet:ipv4=1.2.3.4] $lib.print($node) | spin
Executing query at 2021/05/11 15:22:26.197
...
16909060
complete. 0 nodes in 78 ms (0/sec).
```

We also don't capture the list contents in the following example:

```
$list=$lib.list() $list.append(1) $list.append(2) 
$lib.print("List {list} has {len} elements!", list=$list, len=$lib.len($list))

> List <synapse.lib.stormtypes.List object at 0x7fa11503c100> has 2 elements!

```

I think the original task for for custom reprs for storm objects?

2021-05-13 09:31 UTC, invisig0th approved these changes

2021-05-13 14:02 UTC, invisig0th requested changes
gotta discuss repr output convention quick

2021-05-14 19:26 UTC, invisig0th submitted a review, later dismissed

2021-05-14 19:26 UTC, invisig0th commented on synapse/lib/stormtypes.py
> +        reprs = ["{}: {}".format(await torepr(k), await torepr(v)) for (k, v) in list(self.valu.items())]
for these two, couldn't we just return `repr()` of `toprim()` ?

2021-05-19 18:11 UTC, vEpiphyte approved these changes

2021-05-19 19:15 UTC, merged