WIP: convert storm runtime to base to allow fini
vertexproject/synapse pull request #2203
Opened 2021-05-20 15:29 UTC by invisig0th

2021-05-20 18:21 UTC, vEpiphyte commented on synapse/lib/stormtypes.py
> -    @stormfunc(readonly=True)
Why is this change being made?

2021-05-26 15:33 UTC, vEpiphyte commented on synapse/lib/stormhttp.py
> +
Class docstring

2021-05-26 15:34 UTC, vEpiphyte commented on synapse/lib/stormhttp.py
> +class WebSocket(s_base.Base, s_stormtypes.StormType):
@s_stormtypes.registry.registerType

2021-05-26 15:47 UTC, vEpiphyte commented on synapse/lib/stormhttp.py
> +            return (False, ('BadMesgFormat', {'mesg': mesg}))
```
return (False, ('BadMesgFormat', {'mesg': return (False, ('BadMesgFormat', {'mesg': mesg}))}))  # pragma: no cover
```

2021-05-26 15:49 UTC, vEpiphyte requested changes
few doc changes and error line that can be collapsed down

2021-05-26 15:53 UTC, Cisphyx commented on synapse/lib/stormhttp.py
> +    async def rx(self, timeout=None):
timeout is unused

2021-05-26 15:56 UTC, Cisphyx commented on synapse/lib/stormhttp.py
> +         'type': {'type': 'function', '_funcname': 'tx',
funcname should be `rx`

2021-05-26 17:16 UTC, vEpiphyte approved these changes

2021-05-26 17:17 UTC, merged