Redo tagprop keying
vertexproject/synapse pull request #2221
Opened 2021-05-28 19:54 UTC by rakuy0

Fixes SYN-1988

So that sodes containing tagprops can be jsonified.

2021-06-02 17:12 UTC, invisig0th requested changes

2021-06-02 17:12 UTC, invisig0th commented on synapse/cortex.py
> +            return tagprops.get(tag, {}).get(prop) is not None
Plz make these not do the default dict values get constructed by default ( here and others below ) :D

2021-06-03 21:49 UTC, invisig0th approved these changes

2021-06-03 23:17 UTC, vEpiphyte approved these changes

2021-06-03 23:19 UTC, merged