Changelog for v2.88.0
vertexproject/synapse pull request #2607
Opened 2022-03-21 23:48 UTC by vEpiphyte

2022-03-22 00:39 UTC, Cisphyx commented on CHANGELOG.rst
> +  (`#2606 <https://github.com/vertexproject/synapse/pull/2606>`_)
Wrong PR, should be 2603

2022-03-22 06:07 UTC, invisig0th commented on CHANGELOG.rst
> +    to a ``hash`` type.
Did you mean a `hex` type here?

2022-03-22 06:07 UTC, invisig0th commented on CHANGELOG.rst
> +    to a ``hash`` type.
( and here )

2022-03-22 10:50 UTC, whippit commented on CHANGELOG.rst
> +  ``crypto:payment:input``
crypto:payment:output?

2022-03-23 18:45 UTC, invisig0th requested changes

2022-03-23 19:01 UTC, invisig0th approved these changes

2022-03-23 19:08 UTC, merged