raise NotReady exception when a getAhaProxy is called without aha_clients set (SYN-3489)
vertexproject/synapse pull request #2645
Opened 2022-04-18 22:21 UTC by vEpiphyte

2022-04-19 12:50 UTC, mikemoritz approved these changes

2022-04-19 12:53 UTC, invisig0th requested changes

2022-04-19 12:53 UTC, invisig0th commented on synapse/telepath.py
> +        raise s_exc.NotReady(mesg=mesg)
Refocus this message to be user-perspective rather than developer perspective :D Something like `No aha servers registered.` etc etc

2022-04-20 14:54 UTC, Cisphyx approved these changes

2022-04-20 15:09 UTC, merged