Add Storm uptime command and API (SYN-3658, SYN-3756)
vertexproject/synapse pull request #2728
Opened 2022-06-22 18:22 UTC by mikemoritz

Also fixes a bug in getTotalMemory()

2022-06-22 21:57 UTC, invisig0th requested changes

2022-06-22 23:40 UTC, mikemoritz commented on synapse/lib/storm.py
> +            $lib.print("up {days}, {hrs}, {mins} (since {since})",
TBH I forgot we could repr the type in storm.  Updated.

2022-06-23 11:39 UTC, vEpiphyte commented on synapse/tests/test_lib_stormlib_cell.py
> +class TestsvcApi(s_cell.CellApi, s_stormsvc.StormSvc):
for reference we don't actually need the target cell to implement the StormSvc convention.

2022-06-23 15:06 UTC, vEpiphyte commented on synapse/tests/test_lib_stormlib_cell.py
> +class TestsvcApi(s_cell.CellApi, s_stormsvc.StormSvc):
we could also reuse one of the services from `test_lib_stormsvc` too.

2022-06-23 21:16 UTC, invisig0th approved these changes

2022-06-23 22:10 UTC, merged