inet model bugfixes (SYN-4552, SYN-4561)
vertexproject/synapse pull request #2982
Opened 2023-01-13 18:33 UTC by vEpiphyte

- `inet:dns:soa` properties are now writable.
- `inet:email` norm now catches a python ValueError during splitting and raises a BadTypeValu directly when that happens.

2023-01-13 18:51 UTC, Cisphyx approved these changes

2023-01-13 18:52 UTC, invisig0th requested changes

2023-01-13 18:52 UTC, invisig0th commented on synapse/models/inet.py
> +            mesg = f'Cannot split the email user and fqdn for "{valu}"'
Maybe something about the missing @ sign?  Something like `Email address expected in <user>@<fqdn> format: {valu}` or something?

2023-01-13 21:16 UTC, Cisphyx approved these changes

2023-01-16 17:59 UTC, invisig0th approved these changes

2023-01-16 17:59 UTC, merged