Risk model docstrings
vertexproject/synapse pull request #3027
Opened 2023-02-23 17:23 UTC by therealsilence

- Update docstrings for risk:* model to clarify use.
- Update links in various intro docs.

2023-02-23 18:13 UTC, Cisphyx commented on synapse/models/risk.py
> +                        'doc': 'A user-specified type for the compromise',
missing period

2023-02-23 18:23 UTC, invisig0th requested changes

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                    'doc': 'A threat cluster or subgraph of threat activity, as described by a specific reporter.',
"reporter" might imply a journalist. maybe change to "as reported by a specific organization" ?

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                    'doc': 'A software tool used in threat activity, as described by a specific reporter.',
and here too :)

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'The reporter\'s assessed location of the threat cluster.'}),
Gets a bit wordy, but may want to consider "The reporting orgnizations's" here and below?

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'A user-specified type for the tool.'}),
Another "not necessarily user defined" spot where we should probably use a standard taxonomy type description

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'An authoritative software family for the tool.'}),
This isn't "one of many" authoritative, so i think "the" is correct? Just like "the name of the organization" etc

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'A user-specified alert type.'}),
not user-specified

2023-02-23 18:23 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'A user-specified verdict about why the alert is malicious or benign.'}),
Should probably eliminate analyst/user specified here too. Could be machine specified as well.

2023-02-23 18:45 UTC, reign-git commented on synapse/models/risk.py
> +                        'doc': 'An array of alterate names for the tool, according to the reporter.'}),
alternate

2023-02-23 19:11 UTC, therealsilence commented on synapse/models/risk.py
> +                        'doc': 'A user-specified type for the threat.'}),
Per discussion, "A type for the <foothing>, as a taxonomy entry"

2023-02-28 00:07 UTC, Cisphyx approved these changes

2023-02-28 17:05 UTC, merged