WIP: Add file:archive:entry
vertexproject/synapse pull request #3202
Opened 2023-06-27 20:59 UTC by invisig0th

2023-06-27 21:28 UTC, mbvertex approved these changes

2023-06-30 15:13 UTC, vEpiphyte requested changes

2023-06-30 15:13 UTC, vEpiphyte commented on synapse/tests/test_model_files.py
> +                    :posix:gid=1000
Missing posix perms property

2023-06-30 16:14 UTC, vEpiphyte approved these changes

2023-06-30 16:14 UTC, merged