WIP: SYN-5600: Removing extended form does not properly remove all the props
vertexproject/synapse pull request #3223
Opened 2023-07-07 15:47 UTC by blackout-vtx

- Update `synapse.datamodel.Model.delForm()` to check for extended properties on the form before deletion. If extended props are found, raise exception with names of properties.
- Update tests.

Resolves SYN-5600

2023-07-08 00:07 UTC, vEpiphyte commented on synapse/tests/test_lib_stormlib_modelext.py
> +                self.eq('Form has extended properties: tick', exc.exception.get('mesg'))
The exception would be raises here before the `self.eq()` statement is executed. If you remove one level of indentation you can access the `.exception` property on the context manager to make test assertions on its contents.

2023-07-08 00:11 UTC, vEpiphyte commented on synapse/tests/test_lib_stormlib_modelext.py
> +                self.eq('Form has extended properties: tick, tock', exc.exception.get('mesg'))
indentation

2023-07-08 00:16 UTC, vEpiphyte requested changes
correct test assertions

2023-07-11 18:03 UTC, vEpiphyte approved these changes

2023-07-12 14:17 UTC, invisig0th approved these changes

2023-07-12 14:17 UTC, merged