Model repo labels more concretely
vertexproject/synapse pull request #3341
Opened 2023-09-12 19:52 UTC by rakuy0

Output of a review from @Cisphyx. Modeling github issue labels using tags resulted in awkward things like `rep.github.enhancement` when it wasn't really github asserting things, and even getting the user info could result in `rep.myfoouser.bugfix`, which feels odd if `myfoouser` isn't a user in the cortex. Promoting the label to a more concrete element so we can record things like times and which service account applied the label made a bit more sense.

Only thing missing is the service account that added the label, but that's waiting on the big inet:service update.

2023-09-14 17:08 UTC, vEpiphyte commented on synapse/models/infotech.py
> +                    ('id', ('str', {}), {
do we want to strip whitespace?

2023-09-14 17:08 UTC, vEpiphyte commented on synapse/models/infotech.py
> +                    ('title', ('str', {}), {
do we want to strip whitespace?

2023-09-15 14:26 UTC, invisig0th requested changes

2023-09-15 14:26 UTC, invisig0th commented on synapse/models/infotech.py
> +                ('it:dev:repo:issue:label', ('guid', {}), {
Lets discuss. I think label probably doesn't need the guid abstraction and could likely be just a `:labels` array on the issue node :+1:

2023-10-05 13:48 UTC, invisig0th requested changes

2023-10-05 13:48 UTC, invisig0th commented on synapse/models/infotech.py
> +                ('it:dev:label', {}, (
Ok, i finally grok it :D 

`it:dev:repo:label` -> `it:dev:repo:issue:label`
`it:dev:label` -> `it:dev:repo:label`

final answer ;)

2023-10-10 10:35 UTC, invisig0th approved these changes

2023-10-10 10:35 UTC, merged