SYN-6169: Manually setting parent does not include nested layers in reparented view
vertexproject/synapse pull request #3354
Opened 2023-09-25 20:18 UTC by MichaelSquires

bug: fixed bug when parenting a view to another view with multiple layers and only one of the parent's layers would show up in the child view

2023-09-25 20:40 UTC, MichaelSquires commented
Add migration checks

2023-09-26 16:00 UTC, invisig0th requested changes

2023-09-26 16:00 UTC, invisig0th commented on synapse/lib/view.py
> +        # Add all of the bottom view's layers
It feels odd to handle only the last view with a special case here. We may need to talk this one through just one more time :D

2023-09-29 20:13 UTC, invisig0th approved these changes

2023-10-02 12:52 UTC, merged