Add SYN_LOG_DATEFMT for logging (SYN-6217)
vertexproject/synapse pull request #3362
Opened 2023-10-04 14:25 UTC by vEpiphyte

2023-10-04 15:28 UTC, Cisphyx commented on docs/synapse/devopsguide.rst
> +Custom date formatting strings can also be provided by setting the ``SYN_LOG_DATEFMT`` string. These is expected to be
"These is" should be "This is"

2023-10-04 15:29 UTC, Cisphyx commented on docs/synapse/devopsguide.rst
> +    Milliseconds are not available when using the date formatting option. This will result in a lose of precision for
should be "loss" instead of "lose"

2023-10-04 15:34 UTC, Cisphyx commented on synapse/common.py
> -def setlogging(mlogger, defval=None, structlog=None, log_setup=True):
the docstring for this function could use an update

2023-10-05 13:24 UTC, invisig0th requested changes

2023-10-05 13:24 UTC, invisig0th commented on docs/synapse/devopsguide.rst
> +    SYN_LOG_DATEFMT="%d%m%Y %H:%M:%S"
Lets use `SYN_LOG_DATEFORMAT` here ( no need to rename internal vars or anything ). Clarity is worth more than brevity in this instance :)

2023-10-05 20:13 UTC, invisig0th approved these changes

2023-10-05 22:30 UTC, merged