Fix: Remove a check to deal with tags deleted in parent view, resolves SYN-6391
vertexproject/synapse pull request #3408
Opened 2023-11-02 20:10 UTC by rakuy0

2023-11-06 14:19 UTC, Cisphyx commented on synapse/lib/node.py
> -        if curv is s_common.novalu:
I think you could still use this check to determine whether `name` is added to the list of tags to delete rather than always appending that edit.

2023-11-06 21:18 UTC, invisig0th requested changes

2023-11-06 21:18 UTC, invisig0th commented on synapse/lib/node.py
> +        if self.tags.get(name, s_common.novalu) is not s_common.novalu:
To prep for Syn 3.0 ( and make it easier for cisphyx to merge to the syn 3.0 branch ) please tweak to using `self.getTag(name, default=s_common.novalu)` here :)

2023-11-08 22:09 UTC, Cisphyx approved these changes

2023-11-13 15:18 UTC, invisig0th approved these changes

2023-11-14 16:58 UTC, vEpiphyte commented on synapse/lib/node.py
>          edits.extend(self._getTagPropDel(name))
Does the tagpropdel on name also need to become conditional?

2023-11-14 19:07 UTC, vEpiphyte approved these changes

2023-11-14 19:57 UTC, merged