Add risk:vuln:ext:id property (SYN-5667)
vertexproject/synapse pull request #3447
Opened 2023-12-01 19:06 UTC by vEpiphyte

2023-12-01 19:37 UTC, mikemoritz approved these changes

2023-12-05 16:41 UTC, invisig0th approved these changes

2023-12-05 16:41 UTC, invisig0th commented on synapse/models/risk.py
> +                    ('ext:id', ('str', {'strip': True}), {
Since the whole vuln is being identified via this ID when it comes in from a 3rd party ( and we already have `:reporter` et al, lets just make this `:id` :+1:

2023-12-05 17:09 UTC, invisig0th requested changes
little tweak

2023-12-05 17:24 UTC, invisig0th requested changes

2023-12-05 17:24 UTC, invisig0th commented on synapse/models/risk.py
> +                        'doc': 'An external identifier for the vulnerability.'}),
```suggestion
                        'doc': 'An identifier for the vulnerability.'}),
```

2023-12-05 19:16 UTC, invisig0th approved these changes

2023-12-05 19:27 UTC, merged