SYN-6716: `it:sec:cpe` issues when converting from 2.2->2.3 and 2.3->2.2
vertexproject/synapse pull request #3491
Opened 2024-01-11 20:52 UTC by MichaelSquires

bugfix: Updated CPE code to support better conversions from 2.2->2.3 and vice versa

2024-01-18 13:53 UTC, invisig0th approved these changes

2024-01-19 15:42 UTC, vEpiphyte commented on synapse/tests/test_model_infotech.py
> +            self.eq(r'foo:bar', core.model.type('it:sec:cpe').norm(r'cpe:2.3:a:foo\:bar:*:*:*:*:*:*:*:*:*')[1]['subs']['vendor'])
Can we move this line  / concept to `test_infotech_cpes` ?

2024-01-19 15:43 UTC, vEpiphyte commented on synapse/tests/test_model_inet.py
> +    async def test_cpe_scrape_one_to_one(self):
I put this test in the wrong file :laughing:  lets move it to test_model_infotech

2024-01-22 16:00 UTC, vEpiphyte approved these changes

2024-01-22 19:13 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                    mesg = f'Unable to migrate primary property for {formname}="{formvalu}" (iden: {iden}). Continuing to migrate secondary properties.'
This error message implies that we do migrate the primary property?

2024-01-23 00:27 UTC, invisig0th requested changes

2024-01-23 00:27 UTC, invisig0th commented on synapse/lib/modelrev.py
> +                sodevalu = sode.get('valu')
This logic would preclude us normalizing a secondary property which was flying solo in the storage node. We should probably just let the prop check below stand.

2024-01-23 00:53 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                    subcurv = props.get(subprop.name)
wont `subcurv` be `(valu, stortype)` ?

2024-01-23 00:54 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                propvalu = propvalu[0]
this is slicing subcurv from (valu, stortype) right?

2024-01-23 00:55 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                    if subcurv == subnorm:
wont subcurv be (valu, stortype) and not match subnorm?

2024-01-23 01:29 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                            logger.warning(f'normFormSubs() may not be used to change storage types for {subprop.full}')
wrong function name

2024-01-23 01:46 UTC, vEpiphyte commented on synapse/lib/modelrev.py
> +                    subcurv = props.get(subprop.name)
We can do this check prior to the norm, right?

2024-01-23 17:03 UTC, invisig0th approved these changes

2024-01-23 17:34 UTC, merged