Ensure Nexus events written to the log are always applied (SYN-6807)
vertexproject/synapse pull request #3518
Opened 2024-01-25 18:13 UTC by Cisphyx

2024-01-26 15:00 UTC, Cisphyx reviewed
Performance benchmark of a Cell with a basic Nexus event being called 100k times (50 runs):
```
         min    / max    / avg    / avg per call
master - 0.162s / 0.183s / 0.173s / 0.00000173s
branch - 1.094s / 1.326s / 1.226s / 0.00001226s
diff   - 0.932s / 1.143s / 1.053s / 0.00001053s
```
Moving the lock has no effect, the added time is from ``asyncio.shield``.

2024-01-30 15:37 UTC, invisig0th requested changes

2024-01-30 15:37 UTC, invisig0th commented on synapse/lib/nexus.py
> +            self.applytask = asyncio.create_task(self._eat((nexsiden, event, args, kwargs, meta)))
Any perf measurements? Could we save on task construction by using a single task and a queue?

2024-01-30 15:38 UTC, invisig0th commented on synapse/lib/nexus.py
> +            self.applytask = asyncio.create_task(self._eat((nexsiden, event, args, kwargs, meta)))
sorry, just seeing your perf comment. reading... :D

2024-01-30 17:56 UTC, invisig0th approved these changes

2024-01-30 18:32 UTC, merged