Add aha:name, aha:leader and aha:network to getCellInfo (SYN-6764)
vertexproject/synapse pull request #3519
Opened 2024-01-25 20:56 UTC by vEpiphyte

2024-01-29 17:42 UTC, Cisphyx submitted a review, later dismissed

2024-01-30 15:34 UTC, invisig0th commented on synapse/lib/cell.py
> +                'aha:name': self.conf.get('aha:name'),
I'd like to discuss making this a nested dictionary quick :)

2024-01-30 15:34 UTC, invisig0th requested changes
lets discuss quick :)

2024-02-01 14:36 UTC, invisig0th approved these changes

2024-02-01 15:31 UTC, merged