SYN-6727: more context for easy perm auth deny
vertexproject/synapse pull request #3522
Opened 2024-01-26 15:40 UTC by MichaelSquires

feat: Added context info to the easyperm struct for reporting in AuthDeny.
feat: Added info argument to easyperms init functions.

2024-01-26 15:42 UTC, MichaelSquires commented on synapse/lib/stormlib/easyperm.py
> +import synapse.lib.schemas as s_schemas
remove me

2024-01-26 15:42 UTC, MichaelSquires commented on synapse/tests/test_lib_stormlib_easyperm.py
> +            visi = await core.auth.addUser('visi')
remove me

2024-01-26 15:42 UTC, MichaelSquires commented on synapse/tests/test_lib_stormlib_easyperm.py
> +            #$lib.auth.easyperm.confirm($a, $lib.auth.easyperm.level.admin)
remove me

2024-01-30 15:27 UTC, invisig0th requested changes

2024-01-30 15:32 UTC, MichaelSquires commented on synapse/lib/cell.py
> +            mesg = f'User ({user.name}) has insufficient easyperms level (requires: {permname}){infomsg}.'
I was trying to distinguish between easyperms and regular permissions so the users would (hopefully) understand that they can't use the optic permissions editor to fix this. This was a suggestion from @mikemoritz who submitted the ticket on behalf of a customer.

2024-01-30 15:34 UTC, MichaelSquires commented on synapse/lib/schemas.py
> +                'type': {'type': 'string', 'minLen': 2},
Yeah, maybe? My intent with `info` was to have data that was useful for reporting errors only. The other option is to set `additionalProperties: true` on `info` and just let the keys/values be freeform.

2024-01-30 15:34 UTC, MichaelSquires commented on synapse/lib/schemas.py
> +                'type': {'type': 'string', 'minLen': 2},
Maybe it should be name `errinfo` or something more specific?

2024-01-30 15:35 UTC, MichaelSquires commented on synapse/tests/test_lib_stormlib_vault.py
> +            self.stormIsInErr(f'User (visi2) has insufficient easyperms level (requires: read) type=vault iden={uiden} cmd=vault.set.perm', msgs)
This will get updated accordingly when we settle on the exception message.

2024-01-30 17:28 UTC, closed without merging