SYN-6814: Add note about Synapse not a data lake
vertexproject/synapse pull request #3553
Opened 2024-02-08 19:31 UTC by MichaelSquires

Updated the introduction page with a note about Synapse not being a data lake.

Preview:
![image](https://github.com/vertexproject/synapse/assets/11776738/f38ad209-fee2-4152-8a53-924f9bb7e001)

2024-02-08 20:01 UTC, therealsilence commented
looks good to me :-)

2024-02-08 20:03 UTC, therealsilence approved these changes

2024-02-09 14:31 UTC, invisig0th requested changes
nits ;)

2024-02-09 14:31 UTC, invisig0th commented on docs/synapse/intro.rst
> +    designed to connect to your data sources on demand in order to ingest data **relevant for your analysis** into the
```suggestion
    designed to connect to your data sources on demand in order to ingest data relevant for your analysis into the
```
No need to be quite so forceful ;)

2024-02-09 14:31 UTC, invisig0th commented on docs/synapse/intro.rst
> +    nodes **per day**. In other words, Synapse is not meant to replace your big-data/data-lake storage; Synapse is
```suggestion
    nodes per day. In other words, Synapse is not meant to replace your big-data/data-lake storage; Synapse is
```

2024-02-09 14:31 UTC, invisig0th approved these changes

2024-02-09 14:31 UTC, merged