Some more quorum APIs, resolves SYN-6913, SYN-6914
vertexproject/synapse pull request #3597
Opened 2024-03-01 17:42 UTC by rakuy0

2024-03-04 13:55 UTC, invisig0th requested changes

2024-03-04 13:55 UTC, invisig0th commented on synapse/lib/stormtypes.py
> +        {'name': 'updateMergeVoteComment', 'desc': 'Update the comment associated with your vote on a merge request.',
Lets make these APIs ( and subsequent python APIs and nexus events ) use `set` rather than `update`

2024-03-04 13:55 UTC, invisig0th commented on synapse/lib/view.py
> +            return
This should explode with a `BadState`

2024-03-04 13:55 UTC, invisig0th commented on synapse/lib/view.py
> +
Probably need a `BadState` here too if bytes is None

2024-03-06 15:44 UTC, Cisphyx approved these changes

2024-03-06 19:57 UTC, invisig0th approved these changes

2024-03-06 21:01 UTC, merged