Clamp certdir cname and aha provisioning name values (SYN-6634)
vertexproject/synapse pull request #3609
Opened 2024-03-08 13:54 UTC by vEpiphyte

- Ensure that we do not generate CSRs or make certificates with potentially invalid X509 Common Name length strings.
- Update AHA to prevent creating invalid provisioning requests.

2024-03-08 16:40 UTC, invisig0th requested changes
doc nits

2024-03-08 16:40 UTC, invisig0th commented on synapse/lib/aha.py
> +            mesg = f'Computed hostname value must not exceed 64 characters in length. {hostname=}, len={len(hostname)}'
```suggestion
            mesg = f'Hostname value must not exceed 64 characters in length. {hostname=}, len={len(hostname)}'
```

2024-03-08 16:40 UTC, invisig0th commented on synapse/lib/aha.py
> +            mesg = f'Computed username value must not exceed 64 characters in length. username={username}, len={len(username)}'
```suggestion
            mesg = f'Username value must not exceed 64 characters in length. username={username}, len={len(username)}'
```

2024-03-08 16:40 UTC, invisig0th commented on synapse/lib/certdir.py
> +            mesg = f'certificate name values must be between 1-64 characters. got name={name}, len={len(name)}'
```suggestion
            mesg = f'Certificate name values must be between 1-64 characters. got name={name}, len={len(name)}'
```

2024-03-08 16:40 UTC, invisig0th commented on synapse/lib/certdir.py
> +            mesg = f'csr name values must be between 1-64 characters. got name={name}, len={len(name)}'
```suggestion
            mesg = f'CSR name values must be between 1-64 characters. got name={name}, len={len(name)}'
```

2024-03-08 19:54 UTC, Cisphyx approved these changes

2024-03-11 14:35 UTC, invisig0th approved these changes

2024-03-11 16:34 UTC, merged