Set AHA svcinfo/ready to false conditionally (SYN-7217)
vertexproject/synapse pull request #3705
Opened 2024-05-01 11:56 UTC by vEpiphyte

When tearing down a service, we can no longer know if it is ready. Conditionally clear the ready value.

2024-05-01 17:54 UTC, invisig0th requested changes

2024-05-01 17:54 UTC, invisig0th commented on synapse/tests/test_lib_aha.py
> +                    self.false(ready)  # Ready is  cleared upon restart / setting service down.
```suggestion
                    self.false(ready)  # Ready is cleared upon restart / setting service down.
```

2024-05-02 15:03 UTC, MichaelSquires approved these changes

2024-05-03 15:51 UTC, invisig0th approved these changes

2024-05-03 16:05 UTC, merged