Enh: Prop additions for LNK form, resovles SYN-7680
vertexproject/synapse pull request #3817
Opened 2024-07-17 15:48 UTC by rakuy0

2024-07-17 19:25 UTC, invisig0th requested changes

2024-07-17 19:25 UTC, invisig0th commented on synapse/models/files.py
> +                    ('machineid', ('str', {}), {
Should this have type `it:hostname`?

2024-07-17 21:45 UTC, rakuy0 commented
I have a small goback concerning some indexing of localization/icon data.

2024-07-18 14:36 UTC, invisig0th requested changes

2024-07-18 14:36 UTC, invisig0th commented on synapse/tests/test_model_files.py
> +            self.eq(node.get('machineid'), 'stellarcollapse')
A 1-line test to confirm the relationship from the `file:mime:lnk -> it:hostname` here would be a good idea. Something like:
```
self.len(1, await core.nodes('file:mime:lnk -> it:hostname'))
```

2024-07-19 15:59 UTC, vEpiphyte approved these changes

2024-07-22 15:49 UTC, Cisphyx approved these changes

2024-07-22 19:56 UTC, invisig0th approved these changes

2024-07-22 19:56 UTC, merged