Add light edges to extended model (SYN-6976)
vertexproject/synapse pull request #3824
Opened 2024-07-24 13:38 UTC by Cisphyx

2024-07-24 15:11 UTC, invisig0th requested changes

2024-07-24 15:11 UTC, invisig0th commented on synapse/datamodel.py
> +    def edge(self, name):
Is `name` here really an `edgetype` tuple?

2024-07-24 15:11 UTC, invisig0th commented on synapse/cortex.py
> +        edgedef = {'n1form': n1form, 'verb': verb, 'n2form': n2form}
Could we just send along an `edgetype` tuple here (and above)? I'd like to start trying to make these messages a bit more compact :)

2024-07-24 15:11 UTC, invisig0th commented on synapse/lib/stormlib/modelext.py
> +        {'name': 'addEdge', 'desc': 'Add an extended edge definition to the data model.',
Should probably specify here ( or in the args help ) that the verb must begin with _

2024-07-26 17:11 UTC, invisig0th submitted a review, later dismissed

2024-07-26 20:52 UTC, Cisphyx reviewed
Do we like `[\w\.:]+` (any unicode word characters, `.`, and `:`) and "must be lowercase" as the edge verb restrictions?

2024-07-29 11:39 UTC, invisig0th commented
> Do we like `[\w\.:]+` (any unicode word characters, `.`, and `:`) and "must be lowercase" as the edge verb restrictions?

I think underscore is fine as well. What do we use in the grammar?

2024-07-29 12:13 UTC, Cisphyx commented
> I think underscore is fine as well. What do we use in the grammar?

Underscore actually counts as a word character so that is included. Currently the grammar has no restrictions on the characters used in light edge verbs. This is basically a slightly looser regex than what we use for tags, `(\w+\.)*\w+`

2024-07-29 15:27 UTC, invisig0th approved these changes

2024-07-29 15:40 UTC, merged