WIP: model for rail transportation and shipping
vertexproject/synapse pull request #3833
Opened 2024-08-01 11:22 UTC by invisig0th

2025-01-13 17:50 UTC, therealsilence commented on synapse/models/person.py
> +                    'template': {'phys:object': 'person'},
Is the intent for the phys:object characteristics to represent the "most recent" height/weight/mass/etc? We already have ps:vitals.

Related comment, should ps:vitals inherit phys:object and have things like :height / :weight deprecated?

2025-01-13 17:50 UTC, therealsilence commented on synapse/models/person.py
> +                    'interfaces': ('phys:object',),
I am iffy on having ps:contact inherit phys:object:
- a contact could be for an org (probably would not  include height/weight/mass of "headquarters") as well as a person
- we have ps:vitals, which  can be linked to a ps:contact / ps:person / both.
So it seems the only advantage to putting height/weight/mass on the contact is to have it "one degree closer", but this potentially splits tracking of this data on to two forms (the ps:contact and related ps:vitals...three if you include the "most current" (?) stats on ps:person).

2025-01-13 17:50 UTC, therealsilence commented on synapse/models/transport.py
> +                    'interfaces': ('transport:container',),
Should this inherit transport:vehicle vs. transport:container? (transport:vehicle includes :operator; this would also make it consistent w/the inheritence for transport:sea:vessel and transport:air:craft).

2025-01-13 17:50 UTC, therealsilence commented on synapse/models/transport.py
> +                ('transport:rail:train', ('guid', {}), {
How does this differ from other land-based transport where we need a special form for trains? Currently transport:land:segment is an individual segment. Other land-based transport (besides trains) may include multiple segments / stops (e.g., a bus route, or a standard long-haul trucking route, or even a local FedEx delivery route).

Would a more generic transport:land:route be a better fit for "land transport" that commonly includes multiple segments?

I also found the 'transport:rail:train' name a bit confusing - as the model expands, the naming conventions within transport:* aren't always intuitive as to which forms are "objects" (planes, containers) and which are "instances of moving from one place to the next". tl;dr transport:rail:train sounds like it should be a vehicle/object.

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/material.py
> +                ('phys:contained', {}, (
Something about this is throwing me a little. Because we're using "contained" (vs "contains") it feels like we are emphasizing the object being contained, as opposed to the object that is the container (but also a phys:object) itself. (So focusing on thing 1 that is within thing 2, as opposed to capturing it as thing 2 which contains thing 1). I think this is bothering me because I interpret the container as the primary object and phys:contains would communicate that focus (and be consistent with the phrasing "the period where the container held the object"). However, I'm not at all sure that this actually matters

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/material.py
> +                ('phys:object', {
Would we want to include an :asof prop?

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/person.py
> +                    'template': {'phys:object': 'person'},
do we need to deconflict w/ps:vitals (which has :height and :weight)?

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/person.py
> +                    'interfaces': ('phys:object',),
I'm not clear on the benefits of having phys:object linked to ps:contact - in the case of a person, would I use this to capture something like the info on my ID? (As of this date, I lived at X, and was 5 ft 3 inches and 8 million lbs)? Or would I use phys:object to capture my house at ps:contact:address?

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/transport.py
> +                    'doc': 'A vehicle such as an air craft or sea vessel.'}),
change "air craft" to one word here?

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/transport.py
> +                    'doc': 'Properties common to travel schedules.',
Would we still use transport:schedule in the event that we are modeling a flight (for example), that was supposed to take off at 8am and last 3 hours and arrive at 12pm local time, but was ultimately cancelled? In that case, would we just capture the :scheduled:* prop values and leave :departed:* and :arrived:* empty? Or would we want something like a status property to note that this was scheduled but cancelled?

Actually based on the below it looks like we'd model the transport:schedule but then use transport:segment:status to note that it was cancelled?

2025-01-13 19:40 UTC, mbvertex commented on synapse/models/transport.py
> +                        'doc': 'The segment traveled by the ocupant.'}),
typo - "ocupant"

2025-01-14 16:40 UTC, reign-git commented on synapse/models/geospace.py
> +                    ('geo:locatable', {
Is there any value is breaking the address out to capture key data points even when the full mailing isnt available (e.g., city, state, postal code). A lot of data sources often return city and state information, but not the exact address. This aligns with this ticket - https://vertexproject.atlassian.net/browse/VTX-2660

2025-01-14 16:46 UTC, reign-git commented on synapse/models/geospace.py
> +
Do we want to add a tri:latlong prop to account for latlong values obtained via trilateration?

2025-01-14 17:08 UTC, reign-git commented on synapse/models/material.py
> +                ('phys:object', {
Do we want to include weight here?

2025-01-14 17:09 UTC, reign-git commented on synapse/models/material.py
> +                ('phys:object', {
Do we want a :name and :desc prop?

2025-01-14 17:22 UTC, reign-git commented on synapse/models/material.py
> +                    ('object', ('phys:object', {}), {
Do we wanted to consider naming this prop ":contained"?

2025-01-15 19:45 UTC, invisig0th commented on synapse/models/geospace.py
> +                    ('geo:locatable', {
The `:place:latlong:accuracy` property is used to capture this.

2025-01-15 19:49 UTC, invisig0th commented on synapse/models/geospace.py
> +                    ('geo:locatable', {
Breaking down `geo:address` into subs ( especially automatically ) is outside of the scope for this PR. We could add them later if we decide to break down subs, but parsing arbitrary addresses (especially outside of the US) is difficult bordering in impossible :)

2025-01-15 19:51 UTC, invisig0th commented on synapse/models/geospace.py
> +
The origin of the information does not make it a different field and the geo:locatable interface already accounts for being able to capture accuracy.

2025-01-15 19:51 UTC, invisig0th commented on synapse/models/material.py
> +                ('phys:object', {
It is included. `:mass` is the more accurate term than weight.

2025-01-15 19:52 UTC, invisig0th commented on synapse/models/material.py
> +                ('phys:object', {
I don't think it's safe yet to assume that every instance of a physical object will need a `:name` and `:desc` field. For example, `transport:air:plane`.

2025-01-15 19:54 UTC, invisig0th commented on synapse/models/material.py
> +                ('phys:object', {
Not sure it makes sense on one-time-knowledge forms which will inherit this interface. Anything like vitals will def include a `:time` but open to discussion.

2025-01-15 19:55 UTC, invisig0th commented on synapse/models/material.py
> +                ('phys:contained', {}, (
The node represents the time period where the one object contained the other ( both are separate physical objects ) but def open to discussing the name of the form :+1:

2025-01-15 19:57 UTC, invisig0th commented on synapse/models/person.py
> +                    'template': {'phys:object': 'person'},
Most recent and/or reported ( in the case of entity resolution ). But i def missed the `ps:vitals` and it should def inherit the `phys:object` interface. Good catch!

2025-01-15 19:57 UTC, invisig0th commented on synapse/models/person.py
> +                    'template': {'phys:object': 'person'},
Yep, good catch!

2025-01-15 21:24 UTC, invisig0th commented on synapse/models/transport.py
> +                        ('duration', ('duration', {}), {
will move this to transport:schedule

2025-01-17 18:36 UTC, mbvertex submitted a review, later dismissed

2025-01-17 18:36 UTC, mbvertex commented on synapse/models/person.py
> +                    'doc': "A GUID representing entry in a contact's work history."}),
should this be "an entry" or is shortening it to "entry" fine?

2025-01-17 18:36 UTC, mbvertex commented on synapse/models/transport.py
> +                        ('manufacturer:name', ('ou:name', {}), {
I realized that for it:prod:soft we have :author -> ps:contact, and for it:prod:hardware and then here, for manufacturer, we are instead using ou:org. Is this something that we will eventually want to make consistent across all forms with a "who/what created this"?

2025-01-17 18:42 UTC, invisig0th commented on synapse/models/person.py
> +                    'doc': "A GUID representing entry in a contact's work history."}),
haha, collateral damage from adjusting whitespace. We've also moved away from "A GUID representing" so, i'll update to "An entry in a..." :+1:

2025-01-17 18:45 UTC, invisig0th commented on synapse/models/transport.py
> +                        ('manufacturer:name', ('ou:name', {}), {
Yea, it's probably more correct to make this a `ps:contact` even if we end up tweaking later since it's more flexible. I suppose a vehicle could have been built by an individual. Another use case for the entity:actor abstraction which is coming soon.

2025-01-17 18:48 UTC, invisig0th commented on synapse/models/transport.py
> +                        ('manufacturer:name', ('ou:name', {}), {
Maybe, but the lack of the ability to assert and refine later means we'll probably lean the props toward the more common use case. In this instance, production hardware and vehicles are most commonly made by orgs. Changing to a `ps:contact` would change `:manufacturer:name` to a `ps:name` etc which gets icky.

2025-01-18 13:43 UTC, MichaelSquires requested changes

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/material.py
> +                    'doc': 'A taxonomy for types of contained relationships.'}),
An example (`'ex': '...'`} might be nice here. Based on `phys:contained` description, it seems like this should be something like `liquid` or `grains.large` or something like that?

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/person.py
> +                    'ex': 'robert grey'}),
I keep seeing "Bob Grey" in the code/tests. Is this some pop reference I'm missing?

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/transport.py
> +                ('transport:land:vehicle:type:taxonomy', ('taxonomy', {}), {
Seems weird to have a taxonomy just for land vehicles. Why not a taxonomy for vehicles in general that could be applied to land, sea, air vehicles?

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/transport.py
> +                            'doc': 'The number of occupants of the {vehicle} on this {trip}.'}),
Is there a way to capture how many occupants there were supposed to be vs how many occupants were actually on the trip. I'm thinking about a flight where there are a bunch of no-shows.

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/transport.py
> +                ('transport:stop', {}, (
Does the time/duration of the stop get captured by .seen?

2025-01-18 13:43 UTC, MichaelSquires commented on synapse/models/transport.py
> +
Why no taxonomy for aircraft? Seems like there's plenty of different types of aircraft that you might want to distinguish. Passenger planes, military planes, military cargo, military combat, commercial cargo planes, etc.

2025-01-20 19:31 UTC, Cisphyx commented on synapse/models/material.py
> +                ('phys:contained:type:taxonomy', ('taxonomy', {}), {
Need to add a form for this type as well

2025-01-20 19:34 UTC, Cisphyx commented on synapse/models/person.py
> +                    'doc': 'The person which owns or owned the target node.'}),
These seemed correct before

2025-01-20 19:41 UTC, Cisphyx commented on synapse/models/transport.py
> +                    'doc': 'Cargo being carried by a vehicle on trip.'}),
```suggestion
                    'doc': 'Cargo being carried by a vehicle on a trip.'}),
```

2025-01-20 19:46 UTC, Cisphyx commented on synapse/models/transport.py
> +                            'doc': 'The maxiumum volume the {phys:object} can carry as cargo.'}),
```suggestion
                            'doc': 'The maximum volume the {phys:object} can carry as cargo.'}),
```

2025-01-20 19:47 UTC, Cisphyx commented on synapse/models/transport.py
> +                            'doc': 'The scheduled departure {place}.'}),
```suggestion
                            'doc': 'The scheduled arrival {place}.'}),
```

2025-01-20 19:52 UTC, Cisphyx commented on synapse/models/transport.py
> +                        'doc': 'A type taxonomy for land vehicles.'}),
```suggestion
                        'doc': 'The type of land vehicle.'}),
```

2025-01-20 19:54 UTC, Cisphyx commented on synapse/models/transport.py
> +                    # TODO 3.x modify type to being a taxonomy.
This has been updated to `transport:air:craft:type:taxonomy` in 3.x

2025-01-20 19:57 UTC, Cisphyx commented on synapse/models/transport.py
> +                        'doc': 'Deprecated. Please use transport:occupant.'}),
Do we need to deprecate all of the props if the form is deprecated?

2025-01-21 13:35 UTC, invisig0th commented on synapse/models/transport.py
> +                ('transport:land:vehicle:type:taxonomy', ('taxonomy', {}), {
Each vehicle form is free to have ( or not ) a `:type` which is distinct from the other vehicle types. A unified type would always need to ( and probably would fail to ) start with `land` or `aircraft`. By making them distinct, we only populate the ones we need. We encounter the need for land vehicle types more frequently than plans/trains/vessels because land vehicles come in a wider variety. We may eventually add types to the others.

2025-01-21 13:36 UTC, invisig0th commented on synapse/models/transport.py
> +                ('transport:stop', {}, (
`transport:schedule:duration` is inherited.

2025-01-21 13:39 UTC, invisig0th commented on synapse/models/transport.py
> +                ('transport:land:vehicle:type:taxonomy', ('taxonomy', {}), {
Meh, on second thought, i've got some other minor edits. I'll add types for the others preemptively :) Thanks!

2025-01-21 13:40 UTC, invisig0th commented on synapse/models/transport.py
> +                            'doc': 'The number of occupants of the {vehicle} on this {trip}.'}),
Yes, the vehicle interface contains max occupants vs the trip's occupants. :+1:

2025-01-21 13:40 UTC, invisig0th commented on synapse/models/transport.py
> +
There is a `:type` field which we plan to convert to taxonomy in 3.x.

2025-01-21 13:42 UTC, MichaelSquires commented on synapse/models/transport.py
> +                            'doc': 'The number of occupants of the {vehicle} on this {trip}.'}),
I'm still not sure that would answer the question. Say I have a 747 that has a maximum passenger count of 450. I have 300 scheduled passengers but only 295 of them show up. Is that something that can be modeled with this form? (Is it even something we need to consider? Again, modeling passenger flights seems like the primary use case that I can think of although maybe passenger trains too.)

2025-01-21 13:50 UTC, invisig0th commented on synapse/models/transport.py
> +                    # TODO 3.x modify type to being a taxonomy.
Thanks!

2025-01-21 13:51 UTC, invisig0th commented on synapse/models/person.py
> +                    'ex': 'robert grey'}),
several i suspect ;)

2025-01-21 13:53 UTC, invisig0th commented on synapse/models/transport.py
> +                        'doc': 'Deprecated. Please use transport:occupant.'}),
Dunno? I just did it so any doc strings clarify things on their own.

2025-01-21 14:09 UTC, MichaelSquires approved these changes

2025-01-21 14:09 UTC, Cisphyx commented on synapse/models/transport.py
> +                ('transport:rail:car:type:taxonomy', ('taxonomy', {}), {
Need a form for this type

2025-01-21 15:16 UTC, Cisphyx approved these changes

2025-01-21 16:41 UTC, MichaelSquires approved these changes

2025-01-21 16:41 UTC, merged