Fix backup test stability
vertexproject/synapse pull request #3837
Opened 2024-08-01 20:25 UTC by vEpiphyte

Originally from #3815 - credit to @MichaelSquires

2024-08-01 21:28 UTC, MichaelSquires approved these changes

2024-08-05 13:23 UTC, MichaelSquires commented on synapse/tests/test_lib_cell.py
> +                        orig = s_cell.Cell.BACKUP_SPAWN_TIMEOUT
:facepalm: I know this came from one of my other PRs but I just noticed that we're already patching this value on L1042 above here (from the default of 60s to 8s - not sure why we're kneecapping ourselves here). Seems like the right fix would be to get rid of both patches and just let it run.

2024-08-05 13:24 UTC, MichaelSquires requested changes
Back out this change and remove the patch to 8.0 seconds on L1044 instead.

2024-08-05 19:23 UTC, MichaelSquires approved these changes

2024-08-05 23:34 UTC, invisig0th approved these changes

2024-08-06 12:12 UTC, merged