SYN-7804: fix slab fini order
vertexproject/synapse pull request #3850
Opened 2024-08-12 14:45 UTC by MichaelSquires

2024-08-12 14:58 UTC, invisig0th requested changes

2024-08-12 14:58 UTC, invisig0th commented on synapse/lib/cell.py
> +        self.onfini(slab.fini)
This will leak a reference to the slab if it is ever deleted. We'll need to adjust the behavior of onfini() to fix :)

2024-08-13 13:48 UTC, invisig0th submitted a review, later dismissed

2024-08-13 13:48 UTC, invisig0th commented on changes/06b50ca53d7e7a4a6d482ffd79436884.yaml
> +desc: Fix bug where the calling fini() on the cell slab might cause a hang/timeout
I think we can leave the changelog out for this change :+1:

2024-08-15 12:27 UTC, vEpiphyte approved these changes

2024-08-15 13:54 UTC, invisig0th approved these changes

2024-08-15 14:10 UTC, merged