Enh: `:node` property for `geo:telem`, resolves SYN-7844
vertexproject/synapse pull request #3864
Opened 2024-08-21 20:59 UTC by rakuy0

2024-08-21 21:08 UTC, rakuy0 commented
Do we want to also do a migration from `-(seenat)>` edges to the new property in this PR, leave that as an exercise for later, or just vamp entirely?

2024-08-22 14:08 UTC, invisig0th requested changes

2024-08-22 14:08 UTC, invisig0th commented on docs/synapse/datamodel_deprecation.rst
> +    - Please use the `:node` `geo:telem` property to record the time and location a node was observed.
```suggestion
    - Please use the `geo:telem:node` property to record the observed node.
```

2024-08-22 15:15 UTC, invisig0th approved these changes

2024-08-22 20:09 UTC, merged