improve hot slab ops (SYN-7901)
vertexproject/synapse pull request #3937
Opened 2024-10-01 13:24 UTC by OCBender

2025-01-30 15:07 UTC, invisig0th submitted a review, later dismissed

2025-01-30 15:42 UTC, vEpiphyte requested changes
Looking over this. Will rescind/approve when done.

2025-01-30 22:01 UTC, invisig0th approved these changes

2025-02-03 15:27 UTC, invisig0th submitted a review, later dismissed

2025-02-03 17:19 UTC, Cisphyx commented on synapse/lib/lmdbslab.py
> +            self._sync()
My concern with this is that we now have a window where we have potentially committed index values to a slab which point to a sode with old values.

2025-02-03 17:39 UTC, OCBender commented on synapse/lib/lmdbslab.py
> +            self._sync()
Is this because `sodes` live in another slab?

2025-02-03 17:45 UTC, Cisphyx commented on synapse/lib/lmdbslab.py
> +            self._sync()
Layers have an `self.layrslab.on('commit', self._onLayrSlabCommit)` which saves all dirty sodes first, but since were skipping the `await self.fire('commit')` here we can end up writing those index entries before saving dirty sodes.

2025-02-03 18:20 UTC, OCBender commented on synapse/lib/lmdbslab.py
> +            self._sync()
Ah okay, this makes sense. Its challenging because of the sync/async nature of dual code paths. I've added a new threading event which I believe alleviates the concern though.

2025-02-04 19:13 UTC, invisig0th commented on synapse/lib/lmdbslab.py
> +            self._sync()
threading events involve an actual context switch which is pretty bad for perf

2025-02-04 19:14 UTC, OCBender commented on synapse/lib/lmdbslab.py
> +            self._sync()
I can drop it, though I'm not sure what we can do to alleviate the concern Cisphyx raised.

2025-02-04 19:16 UTC, invisig0th commented on synapse/lib/lmdbslab.py
> +            self._sync()
( and i'm not really sure why we'd need a threading event since all the slab calls are coming from one thread )

2025-02-04 19:33 UTC, invisig0th commented on synapse/lib/lmdbslab.py
> +            self._sync()
Unfortunately, i think we're probably at the point where we need to actually async put() (et al) so we can just use the exising `sync()` to avoid schisms between values being stored directly and values being serialized on `commit` events which will probably be a lot of work. Probably best to make sure we have a ticket to async slab storage operations and table it for now?

2025-02-05 14:14 UTC, OCBender commented on synapse/lib/lmdbslab.py
> +            self._sync()
@invisig0th yeah we have a ticket for asyncify slap ops, if you OK we can close this PR (and associated ticket) as unmerged. I did just push a new commit up which might solve the concern raised, it drops the threading event and wait but introduces a new double check for `syncvnt` which if it fails to assert we return. Let me know if that might pass or you preference on how to proceed. Thanks!

2025-02-10 14:59 UTC, OCBender commented on synapse/lib/lmdbslab.py
> +            self._sync()
From our last discussion we agreed to add some yields in for now and refactor the calls into async at a later date (via a separate ticket). Marking this thread as resolved for now. Thanks!

2025-02-12 16:26 UTC, Cisphyx commented on synapse/lib/jsonstor.py
> +            await asyncio.sleep(0)
I think asyncifying `_incRefObj` so you can add the sleep in the loop is the way to go here, doesn't look like that should make too much of a mess.

2025-02-12 16:29 UTC, Cisphyx commented on synapse/lib/layer.py
> +        await asyncio.sleep(0)
I think you'll need to asyncify these two as well

2025-02-12 16:50 UTC, OCBender commented on synapse/lib/jsonstor.py
> +            await asyncio.sleep(0)
I got the impression we wanted to punt asyncifiying functions to a later date, but I can switch this one up. Will have it up in the next commit.

2025-02-12 16:55 UTC, Cisphyx commented on synapse/lib/jsonstor.py
> +            await asyncio.sleep(0)
Yeah usage of these functions is pretty well contained so it isn't as much of a change as asyncifying the slab methods themselves which will likely have a lot of splatter damage.

2025-02-12 17:00 UTC, OCBender commented on synapse/lib/jsonstor.py
> +            await asyncio.sleep(0)
Makes sense, those two functions have been asyncified :)

2025-02-12 20:00 UTC, Cisphyx commented on synapse/lib/jsonstor.py
> +            await asyncio.sleep(0)
The extra sleeps probably don't hurt anything, but IMO we only need the sleep in the loop removing the meta entries here which could potentially be hot, don't really need this sleep and the other two after single `put` calls.

2025-02-12 21:23 UTC, Cisphyx commented on synapse/tests/test_lib_lmdbslab.py
> +    async def test_lmdbslab_commit_over_max_xactops(self):
Did we still need this test?

2025-02-12 21:23 UTC, Cisphyx approved these changes

2025-02-12 21:33 UTC, OCBender commented on synapse/tests/test_lib_lmdbslab.py
> +    async def test_lmdbslab_commit_over_max_xactops(self):
Maybe? It does pass the max_actops limit with sleep(0). Could it keep it (and drop the sleep line when we asyncify). It also showed a stalling issue w/threading events (though we probably won't use those), it could help expose unexpected issues in future work. I'm also open to dropping it too. Do yo have a preference?

2025-02-12 21:40 UTC, Cisphyx commented on synapse/tests/test_lib_lmdbslab.py
> +    async def test_lmdbslab_commit_over_max_xactops(self):
I don't have a strong preference, it's a quick test so I'm fine with keeping it

2025-02-13 20:03 UTC, vEpiphyte commented on synapse/tests/test_lib_lmdbslab.py
> +    async def test_lmdbslab_commit_over_max_xactops(self):
:eye: checking this

2025-02-13 21:27 UTC, vEpiphyte approved these changes

2025-02-13 22:05 UTC, Cisphyx approved these changes

2025-02-14 13:25 UTC, merged